### PR TITLE
[BUGFIX] fix weapons swap crash dw -> 2h

### LINKED ISSUE #359: Crash Report -154138453
Link:
https://www.wowsims.com/mop/death_knight/frost/#eJztVltoHFUYnv/MZWf/5jI5uTg9tM1mmoZlNXGzSZNtKO6mT0FE2+Kb9CHQKt5AEl/0KYmRtkvEkNJiQpSkgkljK1KFBh9MaMDGYCCUmLQiRa1isV7AgtoijeecuewktW0QVATPbpid77//3zebxY0WxOEQQD/ANMAVgC4C/UR7jZBdpgkW2JAFqrDDFUOqsfuZ9hcOdJgRy2A/ABZbL43pjrF0QRtd0uI5wIjVN6PH+4Rlbky3Z7Y5as+yFh8ALLRGOTDrcGPbaA1Sq1vYHccYXtb4O35ExORmdHvKcVQB8GzU6uFOCx5wBNqO12C59TYvGXWjBDwIbSsxHtvLXZe9eiMi2QwH5r3YPtHaqTE9PiQ+/DIue9Ss3hM6vx0Zl3ix9fIJ3R5njjr4oS7KF0pggjmg8FvHMqfOaxb/syfPa8lj57TEJLEB3wXlP3Zo17/echJaviWo3OFVYB1yly/YQIX+v+u/enYpezXGl/0BMVKpen7OEtt8ZZFYw4vE/umkEXtjkcR//IYkBz8ls0RbIOQzonxFckW2iqVoMgM1M3edOBHUUa3d0RmAP0+pHpjOg79d9T2b8+DQvA82dWIJGkxDYpd4UH3e71y/GoC0jFFmYZF5uCK24h+gN8EEdh3wS2CXAJ+lTyNNWCZQ/TsgJmE8FiGJdew+LEtQU6N6DxG4zJqsawyjkEe3sa2o5kDBTQlmqlQdAIWV9KhF6Ia7l9uVq/+byjmlmAfBs1Fkwa4o57VFoQ6LYUWijNeJToBncjvb7lNCW1kGm9l2LEkUcz/yoOI205DsxBjdshZu4nD0dJBLskW3siq8J1Fu6jR6Vpre7I6I/Ejqk7LOxcuE1rJ7sZJtRn2ON6tiGaUYndOE9eqk6aIaM9Ew3+uOxAiNMD3HFwk0zmqwmBZidEAVzu+/qqKSKkVpJYgy5NcVEgN6P6vFKloZ9hSUGFQfECU9SmTA7zdFgCAnxraEA8S4OlXn+NrlAOl0qMBO1oJJVofliVLOjfmUCHrrHS9xwyr4TADLBZz6KEIbOc9JrGHVaFFO3Q0Qa5AXLY+AeyEyaqRLpWke1YgJFvfllZOC8dQcwnyFB5Ex7rZJeuirRRl4CErkwgJCwxrWwgkFgw+wnZjiIwhFhceXi2roXIWfyeMy/mgu4q6P1uGG4xDwfHdJ+NXvPo7NKrDAQTRToQ6kRXRdTZ2Qlfft5wqJIynJPnZZkL06mzenefCSRstZqS+Zk/P5IlW8wc23CKi5KSSgNGvCBI3/WeVQX/n+81L1n21RKNC5u6v5G5pP2y06d8vGeWfVyJgtKTLCT6n0TQdLrvQmMEITNCZDqfw++Dc83ccewz30kbBm1gpz1VdvCAumFsXUULGUK7eFa4QW8Gxm8PQcBcZ/Kx4E1gvBCtdTdB2+6m1879S439cVsr9bdf+blmVzquKMkzaIyvvpjmyJa3k4u3FoUJyPMztcZCFT9bg8S5k985+I83mm1f3wfSb1NTw3cQ1e3LC3/cn9sUfbO5448Hxsnx1J/EM/cnb3ZtfjNp29EPZ7KP36cOtaHznuF7Ox1kFwN3Ax4/tk/wBpYZOh

RNG Seed: 1275843333

Spell {OtherID: 3, Tag: 2} missing CritMultiplier
Stack Trace:
goroutine 100 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.23.10/x64/src/runtime/debug/stack.go:26 +0x6
github.com/wowsims/mop/sim/core.runSim.func1()
	/home/runner/work/mop/mop/sim/core/sim.go:127 +0x10
panic({0x84...

Tried doing a set swap in a strict sequence

### PR DESCRIPTION
**Pull request by Polynomix**
fixes #359

### CODE REVIEW

**Comment by fredrick-a-n** [comment]
Doing a weapon swap from dw to 2h on frost dk with this change seems to lead to:
`[Player 1] No available actions!`
In the results log, leading to all damage done by the player to become `NaN`

Example: 
[test.txt](https://github.com/user-attachments/files/20962838/test.txt)

**Comment by Polynomix** [comment]
@fredrick-a-n can you link your setup ? I dont have your issue

File: sim/death_knight/frost/frost.go [hunk 1]
```diff
@@ -70,6 +62,17 @@ func (fdk *FrostDeathKnight) Initialize() {
 	fdk.registerPillarOfFrost()
 	fdk.registerRime()
 	fdk.registerThreatOfThassarian()
+
+	fdk.RegisterItemSwapCallback(core.AllWeaponSlots(), func(sim *core.Simulation, slot proto.ItemSlot) {
+		println(sim.CurrentTime.String(), fdk.MainHand().ID, fdk.OffHand().ID)
```
Comment (hillerstorm) [inline sim/death_knight/frost/frost.go:67]: Thanks for fixing this but this line was probably left over :)

Comment (Polynomix) [reply sim/death_knight/frost/frost.go:67]: oopsie
