### PR TITLE
fixed Spell.CanCast crashing on nil target

### LINKED ISSUE #480: Crash Report 1335724968
Link:
https://www.wowsims.com/mop/death_knight/blood/#eJztUV1IFFEUnnPnx3WKvC4W01JwHSgmH2LXCMqXnbWXLch+oV4Hd7ShcdfWCWnJWI1qMwLxRVckIog1MqhekgKTXNMgYZMy+4EkCnzoQR8C3+rMzgoR0UMvGXTuncs533zn535X3kRhF2QAegDGABYAlgHSBHqI0E9Ivc8HFBTQoY5Q8HOBr2UDvHTQNs6YSV8ZlQIFkCtoJieq0oc5YXFW0C6AXEavjouuU0G7c6IysUXl3T+DIJfTPAJPVa1D9tOL6OZVVRp8LeB2+Wtp97ioPFJVHgG5kl5Cxgsv0s5Fb2yV19Pb2KocYyzoon0Q/cbkdfQyMuewTydiHdj3CtaZLmViYYGO5kRZoiM5UUthtDwk4tmHJw5/S1SGAiqfHRW1XpA5lfoezwgUP+XBjBC8PinUjBAF5LvA/WPmT//1keveEZn7/fL/V/dPrZ7bJwRQ4IdECu0I4X5CFN/SsEQXhyXl/ixhN+9I2rWXJNj/ikwRvkCEt4T7SFDvBRJbJtDJe3Wq9G5+c7nrzU8t6pUDWdfehKunn7sm6Iqk9ohRKDK4saRe6aU16Bs96rPwbg8phKubijYbPuQlvw9HPOdLuHaOtH7Kk9Sa/UZzi9HOQkEWZccVqFldb5+OTeo/xtq9rsjPnOJ10wdIJAsrYpU4gt4Lp3zgr9rb0mrYJjtsGo2OlYizo1aLWdMQTbQzOxFvZu2WbTPnBBIMK8Yc46TJnAQrJUVNI8asODtiNibisbbtTIs0OWayyLfilmMZNqrXtq3a61ml1y5Ba6aLT22ot42UheX3JOJtTvJ0o+OpfGzVq1w4v/PXKnNnP+vZ0ujzKypzehC+Axta3Bs=

RNG Seed: 162417517

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.23.10/x64/src/runtime/debug/stack.go:26 +0x6
github.com/wowsims/mop/sim/core.runSim.func1()
	/home/runner/work/mop/mop/sim/core/sim.go:129 +0x10
panic({0xb1300, 0xd95140})
	/opt/hostedtoolcache/go/1.23.10/x64/src/runtime/panic.go:791 +0x1a
github.com/wowsims/mop/sim/core.(*Unit).IsEnabled(...)
	/home/runner/work/mop/mop/sim/core/unit.go:223
github.com/wowsims/mop/sim/core.(*Spell).CanCast(0x208d688, 0x20cb400, 0x0)
	/home/runner/work/mop/mop/sim/core/spell.go:577 +0x4
github.com/wowsims/mop/sim/encounters/default_ai.(*DefaultAI).ExecuteCustomRotation(0x2370240, 0x20cb400)
	/home/runner/work/mop/mop/sim/encounters/default_ai/default_ai.go:65 +0x1f
github.com/wowsims/mop/sim/core.(*Target).ExecuteCustomRotation(0x2095508, 0x20cb400)
	/home/runner/work/mop/mop/sim/core/target_ai.go:61 +0x9
github.com/wowsims/mop/sim/core.(*APLActionCustomRotation).Execute(0x2370a00, ...

### PR DESCRIPTION
**Pull request by vvolodin**
FIxed #480, magmaw encounter performs a tank swap by setting skeleton add's CurrentTarget to nil which causes Spell.CanCast to crash when checking target.IsEnabled().
Although the crash may be fixed in #400 this change makes Spell.CanCast a little bit safer.

### CODE REVIEW

File: sim/core/spell.go [hunk 1]
```diff
@@ -574,7 +574,7 @@ func (spell *Spell) CanCast(sim *Simulation, target *Unit) bool {
 		return false
 	}
 
-	if !target.IsEnabled() {
+	if target == nil || !target.IsEnabled() {
```
Comment (NerdEgghead) [inline sim/core/spell.go:577]: You should make the same change in three other places for consistency: `CanQueue()`, `makeCastFunc()`, and `makeCastFuncSimple()`.

**Review by NerdEgghead — CHANGES_REQUESTED** [review]

File: sim/core/spell.go (hunk 1 above)
Comment (vvolodin) [reply sim/core/spell.go:577]: will do

Comment (vvolodin) [reply sim/core/spell.go:577]: done

**Review by NerdEgghead — APPROVED** [review]
